# Generated by Django 4.2.21 on 2025-05-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_evaluation_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedanswer',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
