# Generated by Django 4.2.27 on 2026-01-11 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_coursemodification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_completion_percent', models.FloatField(default=0)),
                ('modules_completed', models.IntegerField(default=0)),
                ('total_modules', models.IntegerField(default=0)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coursemodification',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_on']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progresses'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_on']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='allow_retake',
            field=models.BooleanField(default=False, help_text='Permettre plusieurs tentatives'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Nombre maximum de tentatives (si retake autorisé)'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='max_score',
            field=models.IntegerField(default=100, help_text='Score maximum pour cette évaluation'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='passing_score',
            field=models.IntegerField(default=60, help_text='Score minimum pour réussir (%)'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='show_correct_answers',
            field=models.BooleanField(default=True, help_text='Montrer les corrections après soumission'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, help_text='Limite de temps en minutes (optionnel)', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text="URL vers l'action à effectuer", max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'Inscription'), ('new_evaluation', 'Nouvelle Évaluation'), ('deadline_reminder', 'Rappel de Deadline'), ('grade_received', 'Note Reçue'), ('certificate_earned', 'Certificat Obtenu'), ('course_update', 'Mise à jour du Cours'), ('general', 'Général')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.evaluation'),
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='evaluations_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='resources_viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='total_evaluations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='total_resources',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1, help_text='Points pour cette question'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='instructor_comment',
            field=models.TextField(blank=True, verbose_name="Commentaire de l'instructeur"),
        ),
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=models.FloatField(blank=True, help_text='Score maximum possible', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed',
            field=models.BooleanField(default=False, help_text="A réussi l'évaluation"),
        ),
        migrations.AddField(
            model_name='submission',
            name='percentage',
            field=models.FloatField(blank=True, help_text='Pourcentage de réussite', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, help_text='Score obtenu', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de correction'), ('graded', 'Noté'), ('late', 'Soumis en retard')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='submittedanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedanswer',
            name='points_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completion_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Bonne réponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=500, verbose_name='Option A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=500, verbose_name='Option B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=500, verbose_name='Option C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=500, verbose_name='Option D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Énoncé de la question'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('image', 'Image'), ('fichier', 'Fichier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submittedanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.question'),
        ),
        migrations.AlterField(
            model_name='submittedanswer',
            name='selected_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('enrollment', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('evaluation', 'student', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='submittedanswer',
            unique_together={('submission', 'question')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='base_course_instruc_222948_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='base_enroll_student_64472a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='base_notifi_recipie_f4002f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['evaluation', 'student'], name='base_submis_evaluat_a4780a_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='base_submis_status_8fece3_idx'),
        ),
        migrations.AddField(
            model_name='resourceview',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='base.resource'),
        ),
        migrations.AddField(
            model_name='resourceview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='base.enrollment'),
        ),
        migrations.RemoveField(
            model_name='submittedanswer',
            name='total_score',
        ),
        migrations.AddIndex(
            model_name='resourceview',
            index=models.Index(fields=['student', 'resource'], name='base_resour_student_a6a6d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceview',
            unique_together={('student', 'resource')},
        ),
    ]
