# Generated by Django 4.2.27 on 2026-01-11 16:17

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_courseprogress_resourceview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='URL publique du certificat (PDF hébergé, etc.)', max_length=500),
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, help_text='Lien vers ressource externe (YouTube, Google Drive, etc.)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='Ou uploader un fichier local', null=True, upload_to='resources/', validators=[base.validators.validate_resource_file]),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student'], name='base_certif_student_de1a09_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issued_on'], name='base_certif_issued__5caf24_idx'),
        ),
    ]
