# Generated by Django 5.2.5 on 2026-01-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_add_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedanswer',
            name='answered',
            field=models.BooleanField(default=False, help_text="L'étudiant a-t-il répondu à cette question?"),
        ),
    ]
